### ISSUE TITLE
coot

### ISSUE THREAD

**Issue by chuckie82** [ExaFEL/gui_demo#1]
@bkpoon 
I pushed a change to the master branch which calls "coot" instead of "bin/coot"
Any thoughts on whether we need to handle both "coot" and "bin/coot"?

**Comment by bkpoon** [comment]
The full path to Coot is constructed with `$COOT_PREFIX`, so the `bin` is needed somewhere. You could add the `bin` to the `os.path.join` command. But if `ccot` is expected to be somewhere in `$PATH`, you could remove the construction of the full path.

**Comment by chuckie82** [comment]
In my case, $COOT_PREFIX is empty. My coot executable comes from ccp4. I will change it so that it will check whether $COOT_PREFIX is empty or not.
