### ISSUE TITLE
gui_demo path

### ISSUE THREAD

**Issue by chuckie82** [ExaFEL/gui_demo#2]
@bkpoon 
Current code assumes gui_demo is placed here:
os.path.join(libtbx.env.build_path.sh_value(), '../modules/gui_demo')
gui_demo folder should be allowed to be placed anywhere. Any thoughts?

**Comment by bkpoon** [comment]
The `gui_demo` folder can be placed anywhere. I just put in `modules` so that it's easier to find the `Coot.py`.

**Comment by chuckie82** [comment]
it's searching for Coot.py under libtbx.env.build_path.sh_value(). Shall we set an environment variable for gui_demo folder path instead?

**Comment by bkpoon** [comment]
Sure, that works. The only important part is being able to locate `Coot.py`.
